// flow-typed signature: 60aab9db2687ed325717dcf7ea1d777f
// flow-typed version: <<STUB>>/babel-preset-es2015-script_v^1.1.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-script/index' {
  declare module.exports: $Exports<'babel-preset-es2015-script'>;
}
declare module 'babel-preset-es2015-script/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-script'>;
}
